Epo 515
OP-TED/model2owl pull request #111
Opened 2022-10-13 16:02 UTC by dbd311

2022-10-23 12:32 UTC, costezki requested changes

2022-10-23 12:32 UTC, costezki commented on .gitignore
> +xpec/.github/*
ant-contrib.jar and saxon...jar shall not be comited to GitHub

2022-10-23 12:32 UTC, costezki commented on test/README.txt.txt
> +$ ant -lib lib/saxon-he-10.6.jar   unit_tests
1. the `readme file` name is Readme.md, please rename. 
2. the readme file shall be ONLY ONE and in the project root.

2022-10-23 12:32 UTC, costezki commented on test/README.txt.txt
> +$ ant -lib lib/saxon-he-10.6.jar   unit_tests
We need a Makefile that 
1. install the necessary libraries
2. runs tests

2022-10-23 12:32 UTC, costezki commented on xspec/.codespellrc
> +[codespell]
why do we need these files? 
Please delete the 4 `.xxx` files. In the future these shall be (Git) ignored if necessary only in the dev environment.

2022-10-23 12:32 UTC, costezki commented on xspec/assembly/enduser-files.xml
> +<?xml version="1.0" encoding="UTF-8"?>
what is the role of this folder? 
I see many technical folders and files at the top level of the repo. Can we hide them somehow?

2022-10-23 13:26 UTC, dbd311 commented
It was discussed with Dragos as well. I will close the PR and write a make
file which define different tasks running automatic tests.

On Sun, Oct 23, 2022, 2:32 PM Eugeniu Costetchi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In .gitignore
> <https://github.com/OP-TED/model2owl/pull/111#discussion_r1002702118>:
>
> > @@ -310,3 +310,6 @@ TSWLatexianTemp*
>  *.synctex.gz
>  *.xpr
>  /data/
> +
> +xpec/.git
> +xpec/.github/*
>
> ant-contrib.jar and saxon...jar shall not be comited to GitHub
> ------------------------------
>
> In test/README.txt.txt
> <https://github.com/OP-TED/model2owl/pull/111#discussion_r1002702351>:
>
> > @@ -0,0 +1,14 @@
> +To run the unit tests:
> +
> +$ cd ${project.dir}
> +$ ant -lib lib/saxon-he-10.6.jar   unit_tests
>
>
>    1. the readme file name is Readme.md, please rename.
>    2. the readme file shall be ONLY ONE and in the project root.
>
> ------------------------------
>
> In xspec/.codespellrc
> <https://github.com/OP-TED/model2owl/pull/111#discussion_r1002702583>:
>
> > @@ -0,0 +1,8 @@
> +[codespell]
>
> why do we need these files?
> Please delete the 4 .xxx files. In the future these shall be (Git)
> ignored if necessary only in the dev environment.
> ------------------------------
>
> In xspec/assembly/enduser-files.xml
> <https://github.com/OP-TED/model2owl/pull/111#discussion_r1002703006>:
>
> > @@ -0,0 +1,31 @@
> +<?xml version="1.0" encoding="UTF-8"?>
>
> what is the role of this folder?
> I see many technical folders and files at the top level of the repo. Can
> we hide them somehow?
> ------------------------------
>
> In test/README.txt.txt
> <https://github.com/OP-TED/model2owl/pull/111#discussion_r1002702429>:
>
> > @@ -0,0 +1,14 @@
> +To run the unit tests:
> +
> +$ cd ${project.dir}
> +$ ant -lib lib/saxon-he-10.6.jar   unit_tests
>
> We need a Makefile that
>
>    1. install the necessary libraries
>    2. runs tests
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OP-TED/model2owl/pull/111#pullrequestreview-1152302561>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADGTSRLCIXLUFSW6KMB7GXTWEUV7NANCNFSM6AAAAAARENZNNE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-23 18:35 UTC, costezki commented on xspec/.codespellrc
> +[codespell]
do we need XSPEC folder? 
I start doubting this. What is its purpose?

2022-10-24 05:17 UTC, dbd311 commented
Xspec is required but I will put it in the make file

On Sun 23 Oct 2022 at 20:35, Eugeniu Costetchi ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In xspec/.codespellrc
> <https://github.com/OP-TED/model2owl/pull/111#discussion_r1002751103>:
>
> > @@ -0,0 +1,8 @@
> +[codespell]
>
> do we need XSPEC folder?
> I start doubting this. What is its purpose?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OP-TED/model2owl/pull/111#discussion_r1002751103>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADGTSRJIG6SLPJQCPVMH56TWEWAQVANCNFSM6AAAAAARENZNNE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-24 21:12 UTC, closed without merging